//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOGSITESI_MVCHomework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makale
    {
        public int MakaleId { get; set; }
        public string MakaleBaslik { get; set; }
        public string MakaleOzet { get; set; }
        public string MakaleIcerik { get; set; }
        public string OkunmaSayisi { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    }
}
